FinalProject02/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='homepage.html'), name='homepage'),
    path('TestApp/', include('TestApp.urls')),
    path('EducationalProgramm/', include('EducationalProgramm.urls', namespace='EducationalProgramm')),
    path('MyInfo/', include('MyInfo.urls', namespace='MyInfo')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MyInfo/urls.py
from django.urls import path
from . import views
app_name = 'MyInfo'

urlpatterns = [
    path ('groupmates/', views.groupmates, name = "groupmates"),
    path ('me/', views.me, name = "me"),
    path ('managers/', views.managers, name = "managers"),
    path ('ep/', views.ep, name = "ep"),
    
    
    

]

TestApp/urls.py
from django.urls import path
from . import views
app_name = 'TestApp'

urlpatterns = [
    path ('show_all_movie/', views.show_all_movie, name = "show_all_movie"),
    path ('show_one_movie/<int:id_movie>', views.show_one_movie, name = "show_one_movie"), 
    path ('show_all_movies_search/', views.show_all_movies_search, name = "show_all_movies_search"),

]

TestApp/models.py
from django.db import models

# Create your models here.
class Movies(models.Model):
    name = models.CharField(max_length=40)
    rating = models.IntegerField()
    year = models.IntegerField()    

    def __str__(self):
        return f'{self.name} - {self.rating}%'


TestApp/templates/base_movies.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset = "UTF-8">
        <title>{%block title %} {% endblock%}</title>
    </head>
   
    <body>
    {% block content %}

    {% endblock %}    

       
    </body>
</html>

TestApp/templates/show_all_movie.html
{% extends 'base_movies.html' %}

{% load static %}  
{%block title %} Все фильмы {% endblock%}


{% block content %}
    <h2>Список фильмов</h2>
    <ul>
        {% for movie in movies%}
        <li><a href='{% url "TestApp:show_one_movie" movie.id %}'>{{ movie }}</a></li>
        {% endfor %}
    </ul>


{% endblock %}

TestApp/templates/show_all_movies_search.html
{% extends 'base_movies.html' %}

{% load static %}  
{%block title %} Поиск {% endblock%}


{% block content %}
    <h2>Фильмы из поиска</h2>

    <ul>
        {% for movie in movies%}
        <li><a href='{% url "TestApp:show_one_movie" movie.id %}'>{{ movie }}</a></li>
        {% endfor %}
    </ul>
    
    <form method="GET">
    <input name="search" type="search" placeholder="Search" aria-label="Search"
    value="{{ search_input }}">
    <button type="submit">Search</button>
    </form>
      <ul>
        {% for movie in m%}
        <li><a href='{% url "TestApp:show_one_movie" movie.id %}'>{{ movie }}</a></li>
        {% endfor %}
    </ul>
    


{% endblock %}

TestApp/templates/show_one_movie.html
{% extends 'base_movies.html' %}

{% load static %}  
{%block title %} Информация о фильме - {{movie.name}} {% endblock%}


{% block content %}
    <h2>Информация о фильме - {{movie.name}}</h2>
    <h2>Рейтинг - {{movie.rating}}</h2>

    

{% endblock %}